# Generated by Django 4.1.3 on 2023-07-26 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_exercise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='createexercise',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workout'),
        ),
    ]
