# Generated by Django 4.1.3 on 2023-07-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_createexercise_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
